# Docker compose file to build/start the whole bfs-IAM stack at once.
# from main repo path:
# build with: docker-compose -f docker-compose.yml build
# start with: docker-compose -f docker-compose.yml up
# close/clean up with: docker-compose -f docker-compose.yml down

version: "3.5"
services:
  keycloak:
    build:
      context: .
      dockerfile: docker/keycloak/Dockerfile
    image: "iam_keycloak"
    networks:
      - imis3
    volumes:
      - ./docker/keycloak:/opt/src
    ports:
      - 48080:8080
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    image: "iam_client"
    networks:
      - imis3
    depends_on:
      - keycloak
    volumes:
      - ./docker/client:/usr/local/iamdocker
      - ./client:/usr/local/iamclient
    ports:
      - 48081:8081
networks:
  imis3:
    name: imis3
