hostname-strict=false
http-enabled=true

db=postgres
db-url=jdbc:postgresql://iam_db/keycloak?currentSchema=keycloak
db-username=keycloak
db-password=secret

spi-theme-static-max-age=-1
spi-theme-cache-themes=false
spi-theme-cache-templates=false
