http-enabled=true

db=postgres
db-url=jdbc:postgresql://db/keycloak?currentSchema=keycloak
db-username=keycloak
db-password=secret

spi-theme-static-max-age=-1
spi-theme-cache-themes=false
spi-theme-cache-templates=false

log-console-format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %m%n
