hostname-strict=false
http-enabled=true

db=postgres
db-url=jdbc:postgresql://iam_db/keycloak?currentSchema=keycloak
db-username=keycloak
db-password=secret

spi-email-template-provider=freemarker

spi-theme-static-max-age=-1
spi-theme-cache-themes=false
spi-theme-cache-templates=false

features=declarative-user-profile

log-console-format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %m%n
