services:
  keycloak:
    build:
      context: ../
      dockerfile: ./docker/keycloak/Dockerfile
    image: ${REGISTRY_HOST}imis3/imis-keycloak:${KC_VERSION}
    env_file:
      - keycloak/keycloak.env
      - shared.env
      - path: keycloak/optional.env
        required: false
#    volumes:
#      - ./keycloak/data:/opt/keycloak/data/import
  client:
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
      args:
        CLIENT_PATH: ${CLIENT_PATH}
    image: ${REGISTRY_HOST}imis3/imis-addressbook:${ABOOK_VERSION}
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    env_file:
      - shared.env
    environment:
      - PHOTON_URL=https://osm.bfs.de/photon
