services:
  mailhog:
    build:
      context: ./mailhog
    image: "iam_mailhog"
    ports:
      - ${MAILHOG_PORT}:8025
    profiles:
      - dev
  ldap:
    build:
      context: ./ldap
    image: "iam_ldap"
    profiles:
      - dev
  db:
    build:
      context: ./db
    image: "iam_db"
    ports:
      - ${DB_PORT}:5432
    profiles:
      - dev
  keycloak:
    build:
      context: ../
      dockerfile: ./docker/keycloak/Dockerfile
    image: "iam_keycloak"
    ports:
      - ${ADMIN_PORT}:8080
    env_file:
      - keycloak/keycloak.env
#    volumes:
#      - ./keycloak/data:/opt/keycloak/data/import
  client:
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
    image: "iam_client"
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - ${PORT}:80
    environment:
      - CLIENT_PATH
      - CLIENT_MODE
      - PROTOCOLL
      - HOSTNAME
      - PORT
      - PHOTON_URL
