ErrorLog /dev/stderr
CustomLog /dev/stdout combined

Listen ${PORT}

ServerName ${PROTOCOLL}://${HOSTSERVERNAME}
ServerAdmin webmaster@localhost

AddOutputFilterByType DEFLATE application/json application/javascript
UseCanonicalName on
SSLProxyEngine On

RedirectMatch 301 "^/$" "${CLIENT_PATH}"

OIDCCryptoPassphrase "exec:/bin/bash -c 'head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64'"
OIDCProviderMetadataURL "${CLIENT_METADATA_URL}"
OIDCClientID iam-client
OIDCClientSecret "${CLIENT_SECRET}"
OIDCRedirectURI "${CLIENT_PATH}redirect_uri"
OIDCRefreshAccessTokenBeforeExpiry 30 logout_on_error
OIDCSessionInactivityTimeout ${SESSION_INACTIVITY_TIMEOUT}
OIDCStateMaxNumberOfCookies 5 true
OIDCCABundlePath /etc/ca-bundle.trust.crt

<LocationMatch "^/(realms|resources)/">
    ProxyPassMatch "http://keycloak:8080"
    ProxyPassReverse "http://keycloak:8080"
</LocationMatch>

<LocationMatch "(${CLIENT_PATH}|/backend/)">
    AuthType openid-connect
    Require valid-user
</LocationMatch>

<Location "/backend/">
    OIDCUnAuthAction 401
    RequestHeader set Authorization "Bearer %{OIDC_access_token}e" env=OIDC_access_token
</Location>

# Pass requests to photon geocoder
#<Location /photon>
#    ProxyPass ${PHOTON_URL}
#    ProxyPassReverse ${PHOTON_URL}
#</Location>

ProxyPass "/backend" "http://keycloak:8080"
ProxyPassReverse "/backend" "http://keycloak:8080"

DocumentRoot "/var/www"
