ErrorLog /dev/stderr
CustomLog /dev/stdout combined

Listen ${PORT}

ServerName ${PROTOCOLL}://${HOSTSERVERNAME}
ServerAdmin webmaster@localhost

LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so
# mod_xml2enc required for mod_proxy_html to prevent "AH01425: I18n support in mod_proxy_html requires mod_xml2enc. Without it, non-ASCII characters in proxied pages are likely to display incorrectly.", see https://gitlab.com/oer-world-map/oerworldmap/-/issues/18
#LoadModule xml2enc_module modules/mod_xml2enc.so
#LoadModule proxy_html_module modules/mod_proxy_html.so
# requirement for proxy_http_module
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule deflate_module modules/mod_deflate.so

AddOutputFilterByType DEFLATE application/json application/javascript
UseCanonicalName on
SSLProxyEngine On

RedirectMatch 301 "^/$" "${CLIENT_PATH}"

OIDCCryptoPassphrase "exec:/bin/bash -c 'head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64'"
OIDCProviderMetadataURL "${CLIENT_METADATA_URL}"
OIDCClientID iam-client
OIDCClientSecret "${CLIENT_SECRET}"
OIDCRedirectURI "${CLIENT_PATH}redirect_uri"
OIDCRefreshAccessTokenBeforeExpiry 30 logout_on_error
OIDCSessionInactivityTimeout ${SESSION_INACTIVITY_TIMEOUT}
OIDCStateMaxNumberOfCookies 5 true
OIDCCABundlePath "${CA_BUNDLE_PATH}"
OIDCCookie ${SESSION_COOKIE_NAME}

<LocationMatch "^/(realms|resources)/">
    ProxyPassMatch "http://keycloak:8080"
    ProxyPassReverse "http://keycloak:8080"
</LocationMatch>

<LocationMatch "(${CLIENT_PATH}|/backend/)">
    AuthType openid-connect
    Require valid-user
</LocationMatch>

<Location "/backend/">
    OIDCUnAuthAction 401
    RequestHeader set Authorization "Bearer %{OIDC_access_token}e" env=OIDC_access_token
</Location>

# Pass requests to photon geocoder
#<Location /photon>
#    ProxyPass ${PHOTON_URL}
#    ProxyPassReverse ${PHOTON_URL}
#</Location>

ProxyPass "/backend" "http://keycloak:8080"
ProxyPassReverse "/backend" "http://keycloak:8080"

DocumentRoot "/var/www"
