# Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

ErrorLog /dev/stderr
CustomLog /dev/stdout combined

<VirtualHost *:80>
    ServerName ${PROTOCOLL}://${SP_HOSTNAME}:${SP_PORT}
    ServerAdmin webmaster@localhost

    AddOutputFilterByType DEFLATE application/json application/javascript
    UseCanonicalName on
    SSLProxyEngine On

    <Location /Shibboleth.sso>
        SetHandler shib
    </Location>

    <Location />
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        ShibRequestSetting entityID ${PROTOCOLL}://${HOSTNAME}:${PORT}/realms/imis3
        RequestHeader set X-SHIB-user "%{uid}e"
        Require shib-session
    </Location>

    # Pass requests to photon geocoder
    <Location /photon>
        ProxyPass ${PHOTON_URL}
        ProxyPassReverse ${PHOTON_URL}
    </Location>

    ProxyPass "/backend" "http://keycloak:8080"
    ProxyPassReverse "/backend" "http://keycloak:8080"

    ProxyPass "/" "http://localhost:${SP_PORT}/" upgrade=websocket
    ProxyPassReverse "/" "http://localhost:${SP_PORT}/"

</VirtualHost>
