# Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

ErrorLog /dev/stderr
CustomLog /dev/stdout combined

<VirtualHost *:80>
    ServerName http://localhost:48081
    ServerAdmin webmaster@localhost

    AddOutputFilterByType DEFLATE application/json application/javascript
    UseCanonicalName on
    SSLProxyEngine On

    <Location /Shibboleth.sso>
        SetHandler shib
    </Location>

    <Location />
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        RequestHeader set X-SHIB-user "%{uid}e"
        require shib-session
    </Location>

    <Location /osm>
        ProxyPass "https://osm.bfs.de"
        ProxyPassReverse "https://osm.bfs.de"
    </Location>

    ProxyPass "/backend" "http://iam-keycloak:8080"
    ProxyPassReverse "/backend" "http://iam-keycloak:8080"

    ProxyPass "/" "http://localhost:8080/"
    ProxyPassReverse "/" "http://localhost:8080/"

</VirtualHost>
