# Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

# Listening on port 80 is configured elsewhere in a Debian installation
#Listen 80

AddOutputFilterByType DEFLATE application/json application/javascript

LoadModule mod_shib /usr/lib/apache2/modules/mod_shib.so

<VirtualHost *:80>
    ServerName http://localhost:48081
    ServerAdmin webmaster@localhost

    UseCanonicalName on

    <Location /Shibboleth.sso>
        SetHandler shib
    </Location>

    <Location />
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        RequestHeader set X-SHIB-user "%{uid}e"
        require shib-session
    </Location>

    ProxyPass "/backend" "http://iam-keycloak:8080"
    ProxyPassReverse "/backend" "http://iam-keycloak:8080"

    ProxyPass "/" "http://localhost:8080/"
    ProxyPassReverse "/" "http://localhost:8080/"

    ErrorLog logs/error.log
    CustomLog logs/access.log combined

</VirtualHost>
