ARG DEBIAN_CODENAME=bookworm
ARG HTTPD_VERSION=2.4
FROM httpd:${HTTPD_VERSION}-${DEBIAN_CODENAME}
LABEL maintainer=tom@intevation.de

#
# Install required packages
#
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y npm libapache2-mod-auth-openidc curl && \
    apt-get -qq clean && rm -rf /var/lib/apt/lists/*

EXPOSE 443

RUN npm install --global yarn

#
# httpd setup
#
ENV SRC=/usr/local/iamclient/
ADD client/package.json client/yarn.lock $SRC
WORKDIR $SRC
RUN yarn install

ADD client $SRC
ARG CLIENT_PATH
ARG REPORT_MAIL="IMIS-Hotline <imisnotifications@example.test>"
RUN VITE_REPORT_MAIL="${REPORT_MAIL}" yarn build --base ${CLIENT_PATH} --outDir /var/www${CLIENT_PATH}

ADD docker/client/ /usr/local/iamdocker/
RUN sed -i "$ a Include /usr/local/iamdocker/client.conf" /usr/local/apache2/conf/httpd.conf

ENV CA_BUNDLE_PATH="/etc/ssl/certs/ca-certificates.crt"

HEALTHCHECK CMD curl --fail ${PROTOCOLL}://${HOSTSERVERNAME}${CLIENT_PATH} || exit 1

CMD ["httpd-foreground"]
