parent=keycloak
import=common/keycloak

styles=css/login.css css/iam.css

meta=viewport==width=device-width,initial-scale=1
locales=de,en

### Imis specific properties
imisInfoUrl=http://example.url
imisFooterContact=https://example.com/impressum.html
imisFooterPrivacy=http://example.url/privacy
imisFooterAccessibility=http://example.url/accessiblity
imisFooterHelp=http://example.url/help

imisLogoPath=
imisLogoAlt=zurück zur Startseite
imisLogoLink=https://example.com/
