parent=keycloak
import=common/keycloak

styles=css/login.css css/iam.css

meta=viewport==width=device-width,initial-scale=1
locales=de,en

### Imis specific properties
imisInfoUrl=http://example.url
imisFooterContact=https://www.bfs.de/DE/service/impressum/impressum_node.html
imisFooterPrivacy=http://example.url/privacy
imisFooterAccessibility=http://example.url/accessiblity
imisFooterHelp=http://example.url/help

imisLogoPath=
imisLogoAlt=<- Zurück zur IMIS Startseite
imisLogoLink=https://www.imis.bfs.de/start/
